### ISSUE TITLE
Issues with payload in POST requests

### ISSUE THREAD

**Issue by francomanca93** [apify/crawlee-python#668]
### Description

When using the `crawlee.http_crawler._http_crawler` module, I'm encountering a `HttpStatusCodeError` with a `404` status code. This error occurs during the `_make_http_request` operation and causes the crawler to reach the maximum number of retries.

The issue with the 404 error in the crawler seems to be related to the way i'm handling the request payload.

![image](https://github.com/user-attachments/assets/f5215110-0b64-4666-9300-975f6d6d1676)

### Steps to Reproduce

1. Initialize a new Crawlee project and set up an `HttpCrawler` with either the `CurlImpersonateHttpClient` or the `HttpxHttpClient`:
```py
import asyncio
import json
from crawlee import Request
from crawlee.http_crawler import HttpCrawler, HttpCrawlingContext
from crawlee.http_clients.curl_impersonate import CurlImpersonateHttpClient
from crawlee.http_clients import HttpxHttpClient

async def main() -> None:
    #http_client = CurlImpersonateHttpClient(
    #    persist_cookies_per_session=True,
    #)
    # Or use HttpxHttpClient:
    http_client = HttpxHttpClient(
        persist_cookies_per_session=True,
    )

    crawler = HttpCrawler(
        http_client=http_client,
        max_requests_per_crawl=20,
    )

    url = "https://www.viagogo.es/Entradas-Deportes/Futbol/Real-Madrid-C-F-Entradas/E-153769088"
    payload = {
        'ShowAllTickets': True,
        'HideDuplicateTicketsV2': False,
        'Quantity': 2,
        'IsInitialQuantityChange': False,
        'PageSize': 20,
        'CurrentPage': 2,
        'SortBy': 'NEWPRICE',
        'SortDirection': 0,
        'Sections': '',
        'Rows': '',
        'Seats': '',
        'SeatTypes': '',
        'TicketClasses': '',
        'ListingNotes': '',
        'PriceRange': '0,100',
        'InstantDelivery': False,
        'EstimatedFees': True,
        'BetterValueTickets': True,
        'PriceOption': '',
        'HasFlexiblePricing': False,
        'ExcludeSoldListings': False,
        'RemoveObstructedView': False,
        'NewListingsOnly': False,
        'PriceDropListingsOnly': False,
        'SelectBestListing': False,
        'ConciergeTickets': False,
        'Method': 'IndexSh'
    }
    payload_bytes = json.dumps(payload).encode()

    print(f"0. Start: {payload_bytes}")

    initial_req = Request.from_url(
        url=url,
        method="POST",
        payload=payload_bytes,
        use_extended_unique_key=True,
    )

    @crawler.router.default_handler
    async def request_handler(context: HttpCrawlingContext) -> None:
        # Handle the response here
        pass

    # Run the crawler
    await crawler.run([initial_req])

if __name__ == '__main__':
    asyncio.run(main())
    
```

2. The crawler encounters a `404` error during the `crawl` operation and raises the following traceback:

   ```
   [crawlee.http_crawler._http_crawler] ERROR Request failed and reached maximum retries
         Traceback (most recent call last):
           File "/Development/scraper/.venv/lib/python3.12/site-packages/crawlee/basic_crawler/_context_pipeline.py", line 62, in __call__
             result = await middleware_instance.__anext__()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           File "/Development/scraper/.venv/lib/python3.12/site-packages/crawlee/http_crawler/_http_crawler.py", line 101, in _make_http_request
             result = await self._http_client.crawl(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           File "/Development/scraper/.venv/lib/python3.12/site-packages/crawlee/http_clients/curl_impersonate.py", line 152, in crawl
             self._raise_for_error_status_code(
           File "/Development/scraper/.venv/lib/python3.12/site-packages/crawlee/http_clients/_base.py", line 153, in _raise_for_error_status_code
             raise HttpStatusCodeError('Error status code returned', status_code)
       crawlee.errors.HttpStatusCodeError: Error status code returned (status code: 404).
   ```

But if I pass the request as this:

```py
    initial_req = Request.from_url(
        url=url,
        method="POST",
        payload=payload,  # payload as dictionary
        use_extended_unique_key=True,
    )
```

The error is the following: 

```
Traceback (most recent call last):
  File "/Development/scraper/src/test_clients.py", line 175, in <module>
    asyncio.run(main())
  File "/Library/Application Support/uv/python/cpython-3.12.7-macos-x86_64-none/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Library/Application Support/uv/python/cpython-3.12.7-macos-x86_64-none/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Application Support/uv/python/cpython-3.12.7-macos-x86_64-none/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Development/scraper/src/test_clients.py", line 159, in main
    initial_req = Request.from_url(
                  ^^^^^^^^^^^^^^^^^
  File "/Development/scraper/.venv/lib/python3.12/site-packages/crawlee/_request.py", line 321, in from_url
    unique_key = unique_key or compute_unique_key(
                               ^^^^^^^^^^^^^^^^^^^
  File "/Development/scraper/.venv/lib/python3.12/site-packages/crawlee/_utils/requests.py", line 126, in compute_unique_key
    payload_hash = _get_payload_hash(payload)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Development/scraper/.venv/lib/python3.12/site-packages/crawlee/_utils/requests.py", line 151, in _get_payload_hash
    return compute_short_hash(payload_in_bytes)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Development/scraper/.venv/lib/python3.12/site-packages/crawlee/_utils/crypto.py", line 17, in compute_short_hash
    hash_object = sha256(data)
                  ^^^^^^^^^^^^
TypeError: object supporting the buffer API required

```
### Environment

- Python version: 3.12
- Crawlee version: 0.4.0

**Comment by francomanca93** [comment]
...following the previous comment...

I have even tried the following for test and it works:

1. I have modified the file `_types.py` line 55:
```py
HttpPayload: TypeAlias = bytes | dict
``` 

2. I have modified the file `_utils.requests.py`:

```py
# ----- before -----
def _get_payload_hash(payload: HttpPayload | None) -> str:
    payload_in_bytes = b'' if payload is None else payload
    return compute_short_hash(payload_in_bytes)
    
# ------- after ------ (only for tests)
def _get_payload_hash(payload: HttpPayload | None) -> str:
    if isinstance(payload, dict):
        import json
        payload = json.dumps(payload).encode('utf-8')
    payload_in_bytes = b'' if payload is None else payload
    return compute_short_hash(payload_in_bytes)
```

The script:

```py
import asyncio
import json
from crawlee import Request
from crawlee.http_crawler import HttpCrawler, HttpCrawlingContext
from crawlee.http_clients.curl_impersonate import CurlImpersonateHttpClient
from crawlee.http_clients import HttpxHttpClient
from crawlee.configuration import Configuration

async def main() -> None:
    http_client = CurlImpersonateHttpClient(
        persist_cookies_per_session=True,
    )
    # Or use HttpxHttpClient:
    #http_client = HttpxHttpClient(
    #    persist_cookies_per_session=True,
    #    configuration=Configuration(verbose_log=True),
    #)

    crawler = HttpCrawler(
        http_client=http_client,
        max_requests_per_crawl=20,
        configuration=Configuration(verbose_log=True),
    )

    url = "https://www.viagogo.es/Entradas-Deportes/Futbol/Real-Madrid-C-F-Entradas/E-153769088"
    payload = {... THE ABOVE PAYLOAD ..}
    payload_bytes = json.dumps(payload).encode() # <--- it doesn't work

    initial_req = Request.from_url(
        url=url,
        method="POST",
        payload=payload,  # payload in dict format
        use_extended_unique_key=True,
    )

    @crawler.router.default_handler
    async def request_handler(context: HttpCrawlingContext) -> None:
        context.log.info(f'Processing {context.request.url} ...')
        response = context.http_response.read().decode('utf-8')
        json_response = json.loads(response)
        context.log.info(f"Total items: {len(json_response['items'])}")
        context.log.info(f"totalCount: {json_response['totalCount']}")
        context.log.info(f"currentPage: {json_response['currentPage']}")
        context.log.info(f"pageSize: {json_response['pageSize']}")
        context.log.info(f"itemsRemaining: {json_response['itemsRemaining']}")

    # Run the crawler
    await crawler.run([initial_req])

if __name__ == '__main__':
    asyncio.run(main())
```


Entire log:

```shell
❯ python src/test_clients.py                                                                                                                                                  ─╯
[crawlee._utils.recurring_task - 23] DEBUG Calling RecurringTask.__init__(func=_log, delay=0:01:00)...
[crawlee._request - 319] DEBUG -----Request payload: {'ShowAllTickets': True, 'HideDuplicateTicketsV2': False, 'Quantity': 2, 'IsInitialQuantityChange': False, 'PageSize': 20, 'CurrentPage': 2, 'SortBy': 'NEWPRICE', 'SortDirection': 0, 'Sections': '', 'Rows': '', 'Seats': '', 'SeatTypes': '', 'TicketClasses': '', 'ListingNotes': '', 'PriceRange': '0,100', 'InstantDelivery': False, 'EstimatedFees': True, 'BetterValueTickets': True, 'PriceOption': '', 'HasFlexiblePricing': False, 'ExcludeSoldListings': False, 'RemoveObstructedView': False, 'NewListingsOnly': False, 'PriceDropListingsOnly': False, 'SelectBestListing': False, 'ConciergeTickets': False, 'Method': 'IndexSh'}


[crawlee.storages._request_queue - 243] DEBUG ---DELETE--- Showing batch data [Request(url='https://www.viagogo.es/Entradas-Deportes/Futbol/Real-Madrid-C-F-Entradas/E-153769088', unique_key='POST|e3b0c442|6793db94|https://www.viagogo.es/entradas-deportes/futbol/real-madrid-c-f-entradas/e-153769088', method='POST', headers=HttpHeaders(root={}), payload={'ShowAllTickets': True, 'HideDuplicateTicketsV2': False, 'Quantity': 2, 'IsInitialQuantityChange': False, 'PageSize': 20, 'CurrentPage': 2, 'SortBy': 'NEWPRICE', 'SortDirection': 0, 'Sections': '', 'Rows': '', 'Seats': '', 'SeatTypes': '', 'TicketClasses': '', 'ListingNotes': '', 'PriceRange': '0,100', 'InstantDelivery': False, 'EstimatedFees': True, 'BetterValueTickets': True, 'PriceOption': '', 'HasFlexiblePricing': False, 'ExcludeSoldListings': False, 'RemoveObstructedView': False, 'NewListingsOnly': False, 'PriceDropListingsOnly': False, 'SelectBestListing': False, 'ConciergeTickets': False, 'Method': 'IndexSh'}, user_data=UserData(crawlee_data=None, label=None), retry_count=0, no_retry=False, loaded_url=None, handled_at=None, id='ykSDp6ltgy8G3xw', json_=None, order_no=None)]...
[crawlee.storages._request_queue - 246] DEBUG Added 1 requests to the queue, response: processed_requests=[ProcessedRequest(id='ykSDp6ltgy8G3xw', unique_key='POST|e3b0c442|6793db94|https://www.viagogo.es/entradas-deportes/futbol/real-madrid-c-f-entradas/e-153769088', was_already_present=False, was_already_handled=False)] unprocessed_requests=[]
[crawlee.storages._request_queue - 247] DEBUG ---DELETE--- Response: {'processed_requests': [{'id': 'ykSDp6ltgy8G3xw', 'unique_key': 'POST|e3b0c442|6793db94|https://www.viagogo.es/entradas-deportes/futbol/real-madrid-c-f-entradas/e-153769088', 'was_already_present': False, 'was_already_handled': False}], 'unprocessed_requests': []}
[crawlee.memory_storage_client._memory_storage_client - 138] DEBUG Storage was already purged on start.
[crawlee._autoscaling.autoscaled_pool - 122] DEBUG Starting the pool
[crawlee.http_crawler._http_crawler - 217] INFO  Current request statistics:
┌───────────────────────────────┬──────────┐
│ requests_finished             │ 0        │
│ requests_failed               │ 0        │
│ retry_histogram               │ [0]      │
│ request_avg_failed_duration   │ None     │
│ request_avg_finished_duration │ None     │
│ requests_finished_per_minute  │ 0        │
│ requests_failed_per_minute    │ 0        │
│ request_total_duration        │ 0.0      │
│ requests_total                │ 0        │
│ crawler_runtime               │ 0.024998 │
└───────────────────────────────┴──────────┘
[crawlee._utils.system - 65] DEBUG Calling get_cpu_info()...
[crawlee._autoscaling.autoscaled_pool - 213] INFO  current_concurrency = 0; desired_concurrency = 2; cpu = 0; mem = 0; event_loop = 0.0; client_info = 0.0
[crawlee.events._event_manager - 125] DEBUG LocalEventManager.on.listener_wrapper(): Awaiting listener task...
[crawlee.statistics._statistics - 239] DEBUG Persisting state of the Statistics (event_data=is_migrating=False).
[crawlee.events._event_manager - 127] DEBUG LocalEventManager.on.listener_wrapper(): Listener task completed.
[crawlee.events._event_manager - 135] DEBUG LocalEventManager.on.listener_wrapper(): Removing listener task from the set...
[crawlee.storages._request_queue - 502] DEBUG Queue head still returned requests that need to be processed (or that are locked by other clients)
[crawlee._autoscaling.autoscaled_pool - 240] DEBUG Scheduling a new task
[crawlee.storages._request_queue - 480] DEBUG There are still ids in the queue head that are pending processing ({"queue_head_ids_pending": 1})
[crawlee._autoscaling.autoscaled_pool - 240] DEBUG Scheduling a new task
[crawlee.storages._request_queue - 480] DEBUG There are still ids in the queue head that are pending processing ({"queue_head_ids_pending": 1})
[crawlee._autoscaling.autoscaled_pool - 236] DEBUG Not scheduling new tasks - already running at desired concurrency
[crawlee.storages._request_queue - 283] DEBUG ---DELETE--- Fetching request with ID: ykSDp6ltgy8G3xw
[crawlee.storages._request_queue - 285] DEBUG ---DELETE--- Fetched request: url='https://www.viagogo.es/Entradas-Deportes/Futbol/Real-Madrid-C-F-Entradas/E-153769088' unique_key='POST|e3b0c442|6793db94|https://www.viagogo.es/entradas-deportes/futbol/real-madrid-c-f-entradas/e-153769088' method='POST' headers=HttpHeaders(root={}) payload={'ShowAllTickets': True, 'HideDuplicateTicketsV2': False, 'Quantity': 2, 'IsInitialQuantityChange': False, 'PageSize': 20, 'CurrentPage': 2, 'SortBy': 'NEWPRICE', 'SortDirection': 0, 'Sections': '', 'Rows': '', 'Seats': '', 'SeatTypes': '', 'TicketClasses': '', 'ListingNotes': '', 'PriceRange': '0,100', 'InstantDelivery': False, 'EstimatedFees': True, 'BetterValueTickets': True, 'PriceOption': '', 'HasFlexiblePricing': False, 'ExcludeSoldListings': False, 'RemoveObstructedView': False, 'NewListingsOnly': False, 'PriceDropListingsOnly': False, 'SelectBestListing': False, 'ConciergeTickets': False, 'Method': 'IndexSh'} user_data=UserData(crawlee_data=None, label=None) retry_count=0 no_retry=False loaded_url=None handled_at=None id='ykSDp6ltgy8G3xw' json_=None order_no=Decimal('1731076460936.870098')
[crawlee.storages._request_queue - 553] DEBUG Skipping request from queue head, already in progress or recently handled ({"id": "ykSDp6ltgy8G3xw", "unique_key": "POST|e3b0c442|6793db94|https://www.viagogo.es/entradas-deportes/futbol/real-madrid-c-f-entradas/e-153769088", "in_progress": true, "recently_handled": false})
[crawlee._autoscaling.autoscaled_pool - 291] DEBUG Worker task finished
[crawlee.storages._request_queue - 490] DEBUG There are still requests in progress (or zombie) ({"in_progress": ["ykSDp6ltgy8G3xw"]})
[crawlee.storages._request_queue - 553] DEBUG Skipping request from queue head, already in progress or recently handled ({"id": "ykSDp6ltgy8G3xw", "unique_key": "POST|e3b0c442|6793db94|https://www.viagogo.es/entradas-deportes/futbol/real-madrid-c-f-entradas/e-153769088", "in_progress": true, "recently_handled": false})
[crawlee._autoscaling.autoscaled_pool - 238] DEBUG Not scheduling new task - no task is ready
[crawlee._utils.system - 75] DEBUG Calling get_memory_info()...
[crawlee.events._event_manager - 125] DEBUG LocalEventManager.on.listener_wrapper(): Awaiting listener task...
[crawlee.events._event_manager - 125] DEBUG LocalEventManager.on.listener_wrapper(): Awaiting listener task...
[crawlee.events._event_manager - 127] DEBUG LocalEventManager.on.listener_wrapper(): Listener task completed.
[crawlee.events._event_manager - 135] DEBUG LocalEventManager.on.listener_wrapper(): Removing listener task from the set...
[crawlee.events._event_manager - 127] DEBUG LocalEventManager.on.listener_wrapper(): Listener task completed.
[crawlee.events._event_manager - 135] DEBUG LocalEventManager.on.listener_wrapper(): Removing listener task from the set...
[crawlee.storages._request_queue - 490] DEBUG There are still requests in progress (or zombie) ({"in_progress": ["ykSDp6ltgy8G3xw"]})
[crawlee.storages._request_queue - 553] DEBUG Skipping request from queue head, already in progress or recently handled ({"id": "ykSDp6ltgy8G3xw", "unique_key": "POST|e3b0c442|6793db94|https://www.viagogo.es/entradas-deportes/futbol/real-madrid-c-f-entradas/e-153769088", "in_progress": true, "recently_handled": false})
[crawlee._autoscaling.autoscaled_pool - 238] DEBUG Not scheduling new task - no task is ready
[crawlee.storages._request_queue - 490] DEBUG There are still requests in progress (or zombie) ({"in_progress": ["ykSDp6ltgy8G3xw"]})
[crawlee.storages._request_queue - 553] DEBUG Skipping request from queue head, already in progress or recently handled ({"id": "ykSDp6ltgy8G3xw", "unique_key": "POST|e3b0c442|6793db94|https://www.viagogo.es/entradas-deportes/futbol/real-madrid-c-f-entradas/e-153769088", "in_progress": true, "recently_handled": false})
[crawlee._autoscaling.autoscaled_pool - 238] DEBUG Not scheduling new task - no task is ready
[crawlee._utils.system - 65] DEBUG Calling get_cpu_info()...
[crawlee._utils.system - 75] DEBUG Calling get_memory_info()...
[crawlee.http_crawler._http_crawler - 169] INFO  Processing https://www.viagogo.es/Entradas-Deportes/Futbol/Real-Madrid-C-F-Entradas/E-153769088 ...
[crawlee.http_crawler._http_crawler - 172] INFO  Total items: 20
[crawlee.http_crawler._http_crawler - 173] INFO  totalCount: 73
[crawlee.http_crawler._http_crawler - 174] INFO  currentPage: 2
[crawlee.http_crawler._http_crawler - 175] INFO  pageSize: 20
[crawlee.http_crawler._http_crawler - 176] INFO  itemsRemaining: 33
[crawlee.events._event_manager - 125] DEBUG LocalEventManager.on.listener_wrapper(): Awaiting listener task...
[crawlee.events._event_manager - 125] DEBUG LocalEventManager.on.listener_wrapper(): Awaiting listener task...
[crawlee.events._event_manager - 127] DEBUG LocalEventManager.on.listener_wrapper(): Listener task completed.
[crawlee.events._event_manager - 135] DEBUG LocalEventManager.on.listener_wrapper(): Removing listener task from the set...
[crawlee.events._event_manager - 127] DEBUG LocalEventManager.on.listener_wrapper(): Listener task completed.
[crawlee.events._event_manager - 135] DEBUG LocalEventManager.on.listener_wrapper(): Removing listener task from the set...
[crawlee._autoscaling.autoscaled_pool - 291] DEBUG Worker task finished
[crawlee._autoscaling.autoscaled_pool - 254] DEBUG `is_finished_function` reports that we are finished
[crawlee._autoscaling.autoscaled_pool - 263] DEBUG Terminating - no running tasks to wait for
[crawlee._autoscaling.autoscaled_pool - 149] INFO  Waiting for remaining tasks to finish
[crawlee._autoscaling.autoscaled_pool - 159] DEBUG Pool cleanup finished
[crawlee.statistics._statistics - 239] DEBUG Persisting state of the Statistics (event_data=is_migrating=False).
[crawlee.http_crawler._http_crawler - 467] INFO  Final request statistics:
┌───────────────────────────────┬──────────┐
│ requests_finished             │ 1        │
│ requests_failed               │ 0        │
│ retry_histogram               │ [1]      │
│ request_avg_failed_duration   │ None     │
│ request_avg_finished_duration │ 1.332043 │
│ requests_finished_per_minute  │ 43       │
│ requests_failed_per_minute    │ 0        │
│ request_total_duration        │ 1.332043 │
│ requests_total                │ 1        │
│ crawler_runtime               │ 1.407498 │
└───────────────────────────────┴──────────┘
```

**Comment by vdusek** [comment]
Hi @francomanca93, this issue should be fixed now. We're releasing a new patch version, 0.4.2, next week. If you'd like to check it out sooner, you can try the latest beta version - https://pypi.org/project/crawlee/#history.

**Comment by Mantisus** [comment]
Hey @francomanca93, `payload` should be `bytes`
```python
payload_bytes = urlencode(payload).encode()
```
will fix it for you.
